apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: fraud-detection
  labels:
    app: flask
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
        version: "1.0"
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: flask
          image: jpatel6625/fraud-detection-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5005
              protocol: TCP
          env:
            - name: APP_BENTOML_URL
              value: http://bentoml:3000/predict
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: fraud-detection
  labels:
    app: flask
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - name: http
      port: 80
      targetPort: 5005
      protocol: TCP