apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: fraud-detection
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: fraud-detection
  labels:
    app: mlflow
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
        version: "1.0"
    spec:
      initContainers:
        - name: db-cleanup
          image: busybox
          command: ["sh", "-c", "rm -f /app/mlruns/mlflow.db && echo 'Cleaned mlflow.db'"]
          volumeMounts:
            - name: mlflow-data
              mountPath: /app/mlruns
      containers:
        - name: mlflow
          image: jpatel6625/fraud-detection-mlflow:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 12
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: mlflow-data
              mountPath: /app/mlruns
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: fraud-detection
  labels:
    app: mlflow
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP